appconfig:
  secret: API_SECRET
  key: API_KEY
  port: APP_PORT
epiphan:
  recording_location: EPIPHAN_RECORDING_LOCATION
  workdir_location: EPIPHAN_WORKING_DIRECTORY_LOCATION
  archive_location: EPIPHAN_ARCHIVED_RECORDING_LOCATION
plugnmeet:
  host: PLUG_N_MEET_SERVER_DOMAIN
  key: PLUG_N_MEET_API_KEY
  secret: PLUG_N_MEET_SECRET
  recording_location: PLUG_N_MEET_RECORDING_LOCATION
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  username: ""
  password: ""
  db: 0
opencast:
  host: OPENCAST_HOSTNAME
  username: OPENCAST_USERNAME
  password: OPENCAST_PASSWORD
  default_series: PlugNMeet recordings
  # Copies most of the metadata from series rather than predefined metadata below
  copy_metadata_from_series: true
  default_acl: public
  create_without_series: true
  event_title_prefix: PlugNMeet recording
  metadata: {
    license: 'ALL RIGHTS RESERVED',
    # This corresponds to Opencast language list entry
    language: 'en',
    publishers: [ 'PlugNMeet recorder' ],
    description: "This is the default description of PlugNMeet recording",
    location: "PlugNMeet conference",
    creators: [ "PlugNMeet" ],
    rights: "",
    contributors: [ ],
    subjects: [ ]
  }
  # Custom ACL configuration that will be ingested with the event for more information https://docs.opencast.org/r/14.x/developer/#api/types/#acl
  custom_acl_config: [
    {
      "action": "write",
      "role": "ROLE_ADMIN"
    },
    {
      "action": "read",
      "role": "ROLE_USER"
    }
  ]
  use_custom_acl_config: true
  # IMPORTANT: Currently it seems opencast has a bug where it doesn't properly parse json values so all configuration params need to be strings
  processing_config: {
    workflow: 'schedule-and-upload',
    configuration: {
      'straightToPublishing': 'true'
    }
  }
mongodb:
  host: MONGODB_HOST
  database: MONGODB_DATABASE
  port: MONGODB_PORT